version: '3.9'

services:
  app:
    image: username/zogakzogak:latest
    container_name: pieceofpeace-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod 