name: ZogakZogak CI/CD with GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-on-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 by running manual deployment steps
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~
            sudo rm -rf ZogakZogak

            git clone https://github.com/Stravinsken/ZogakZogak.git
            
            cd ZogakZogak

            cat <<EOF > .env
            ${{ secrets.ENV_FILE_CONTENT }}
            EOF

            chmod +x ./gradlew

            ./gradlew bootJar --no-daemon

            sudo docker compose up --build -d