name: ZogakZogak CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/ZogakZogak
            git pull origin main
            ./gradlew bootJar                     # EC2에서 JAR 새로 빌드
            sudo docker compose down               # 기존 컨테이너 종료
            sudo docker compose build --no-cache  # 새 이미지 빌드
            sudo docker compose up -d              # 새 컨테이너 실행
            sudo docker compose ps                 # 상태 확인
