name: ZogakZogak CI/CD with GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ZogakZogak
            git pull origin main
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            chmod +x ./gradlew
            ./gradlew bootJar --no-daemon
            sudo docker compose up --build -d
